#!/bin/bash

rm -rf testCJS
mkdir testCJS
echo 'const { arg } = require("../scripts/testArg");' > testCJS/cjs.js
grep -E '\/\* Node:' build/README.md\
  | sed -E 's/.*import (\{ )?([a-zA-Z]+)( })? from[^"]*([^;]+);/var \1\2\3 = require(\4);\
    try {\
      console.log(\2.name || \2);\
      \2(arg(), arg());\
    } catch(e) {\
      try {\
        \2(arg(() => {}), arg(() => {}));\
      } catch {\
        if (e instanceof TypeError) {\
          throw e;\
        }\
      }\
    }/'\
  >> testCJS/cjs.js

sed -E -i -e 's/ ([A-Z][a-zA-Z]+\()[^;]+/ new \1)/g' testCJS/cjs.js

cd build
npm link

cd ../testCJS
npm link froebel

node cjs
cd .. && rm -r testCJS