export { default as ident } from './ident'
export { default as partial } from './partial'
export { default as forward } from './forward'
export { default as callAll } from './callAll'
export { default as debounce } from './debounce'
export { default as throttle } from './throttle'
